### ISSUE TITLE
module 'torkit3d._C' has no attribute 'sample_farthest_points_cuda' #2

### ISSUE THREAD

**Issue by pyr0ken** [zyc00/Point-SAM#10]
Hello, I get this error when using sample_farthest_points:
```
.../.local/lib/python3.10/site-packages/torkit3d/ops/sample_farthest_points.py", line 13, in forward
    index = _C.sample_farthest_points_cuda(points, num_samples)
AttributeError: module 'torkit3d._C' has no attribute 'sample_farthest_points_cuda'
```
I installed torkit3d using this command : 
```bash
pip install "git+https://github.com/Jiayuan-Gu/torkit3d.git"
```
This is the installed package‌ :
![image](https://github.com/user-attachments/assets/d19c9f69-a8de-402d-8a6c-a0674f49006f)

**Comment by Jiayuan-Gu** [comment]
Please add `FORCE_CUDA=1` as the env variable: `FORCE_CUDA=1 pip install "git+https://github.com/Jiayuan-Gu/torkit3d.git"`.
Or you can use replace torkit3d with pytorch3d for the FPS (farthest point sampling).

**Comment by pyr0ken** [comment]
Thank you !
