### ISSUE TITLE
How to use the model

### ISSUE THREAD

**Issue by instabaines** [zyc00/Point-SAM#2]
Hi, 
Thank you for sharing this work. 

Can you provide more information for creating the inputs for the model?
For example the parameters prompt_coords and prompt_labels are not very clear. It will be very helpful to include more descriptions. 

Thanks

**Comment by zyc00** [comment]
Thanks for you advise! We've added a guide script in "scripts/inference.py". This script provides some basic dimension information. And another demo for point cloud segmentation is also available now in the "demo" folder. You can find the whole point cloud annotation pipeline and frontend in this demo. Also, if you want to know how our model works for meshes, please check this repo for more information: https://github.com/zyc00/point-sam-demo. Feel free to ask me if you have any other questions.

**Comment by orttak** [comment]
@instabaines  Did you run the model in your local? I try last 3 days but I couldn't make it. 
my data is around 200MB and I also get this below cuda out of memory error. System needs too much memory. 


torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 45.79 GiB. GPU 0 has a total capacity of 15.71 GiB of which 13.50 GiB is free. Process 437190 has 1.62 GiB memory in use. Of the allocated memory 1.34 GiB is allocated by PyTorch, and 107.72 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by sfengpeng** [comment]
> Thanks for you advise! We've added a guide script in "scripts/inference.py". This script provides some basic dimension information. And another demo for point cloud segmentation is also available now in the "demo" folder. You can find the whole point cloud annotation pipeline and frontend in this demo. Also, if you want to know how our model works for meshes, please check this repo for more information: https://github.com/zyc00/point-sam-demo. Feel free to ask me if you have any other questions.

Hello, yuchen , thanks for your great work! When I use the mask prompts derived from the previous predictions, I get worse predictions than just prompt Point-SAM point prompts. Could you further add the usage of the mask prompts in the scripts?
