### ISSUE TITLE
Python-cuda-torkit3d-installation error

### ISSUE THREAD

**Issue by orttak** [zyc00/Point-SAM#3]
I would like to try model but I have problem about dependcies. Pytorch,CUDA etc. Is there any chances you can upload requirements.txt or docker image to try to model.  I always get error when I start to install torkit3d.
Thanks

**Comment by orttak** [comment]
I solve this problem with below settings but I coudn'r run model for my point cloud. I hope below settings helps for future users

I've note tested Dockerfile but I use nvidia/cuda:12.1.0-devel-ubuntu20.04 as base image. If I will test I will update this comment.

[installation_notes.md](https://github.com/user-attachments/files/16623146/installation_notes.md)
[requirements.txt](https://github.com/user-attachments/files/16623147/requirements.txt)
[conda.txt](https://github.com/user-attachments/files/16623148/conda.txt)
[Dockerfile.txt](https://github.com/user-attachments/files/16623164/Dockerfile.txt)

**Comment by jeb2112** [comment]
I had similar difficulties, but with the third-party apex build, which flags different versions of cuda toolkit and pytorch-cuda as a compile error. Used these two commands to get the compatible cuda for 12.4:
```
conda install --solver=libmamba nvidia/label/cuda-12.4.0::cuda-toolkit --no-channel-priority -y
conda install --solver=libmamba pytorch-cuda pytorch torchvision -c pytorch -c nvidia -y --no-channel-priority
```
