### ISSUE TITLE
About the mask proposal

### ISSUE THREAD

**Issue by LilRedWu** [zyc00/Point-SAM#4]
Very interesting and solid work!  Can the Point-sam propose all-class agnostic masks like  2D SAM or Mask3D?  Will the training code be released?

**Comment by LilRedWu** [comment]
Will the training code be released？

**Comment by lziiid** [comment]
> Thanks for your interest. The training code is already already released.

Hello, I want to test the zero-shot object proposal generation capability following Appendix B.1 in your fantastic paper. Could you please release the code for that?
